chore(backend): add checks to fail CI if tests or quality gate fail

diff --git a/.github/workflows/ci_backend.yml b/.github/workflows/ci_backend.yml
--- a/.github/workflows/ci_backend.yml
+++ b/.github/workflows/ci_backend.yml
@@ -58,6 +58,8 @@ jobs:
     name: Run tests with coverage
     runs-on: ubuntu-latest
     needs: setup
+    outputs:
+      outcome: ${{ steps.run-tests.outcome }}
     env:
       TESTCONTAINERS_HOST: 127.0.0.1
 
@@ -160,6 +162,8 @@ jobs:
     defaults:
       run:
         working-directory: back
+    outputs:
+      outcome: ${{ steps.quality-gate.outcome }}
 
     steps:
       - name: Checkout code
@@ -238,3 +242,28 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           flags: backend
           files: ./back/coverage/clover.xml
+
+  check:
+    name: Check requirements
+    needs:
+      - test
+      - quality
+    runs-on: ubuntu-latest
+    steps:
+      # fail workflow if quality requirements not met
+      # this allows to explicitly specify what went wrong, as we used continue-on-error previously
+      - name: Check requirements
+        if: ${{ needs.test.outputs.outcome == 'failure' || needs.quality.outputs.outcome == 'failure' }}
+        run: |
+          echo "Job failed :"
+          if [ "${{ steps.run-backend-tests.outcome }}" == "failure" ]; then
+            echo "Coverage checks have not been met. See step 'Run tests and generate coverage report' output, and coverage report"
+          fi
+          if [ "${{ steps.quality-gate.outcome }}" == "failure" ]; then
+            echo "Code quality gate check failed. See step 'SonarQube Quality Gate Check'"
+          fi
+          exit 1
+    
+            
+            
+            
